// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: adr_ingest.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getADRIngestCursor = `-- name: GetADRIngestCursor :one
SELECT scope_kind, scope_key, last_path, last_checksum, updated_at
FROM adr_ingest_cursors
WHERE scope_kind = $1 AND scope_key = $2
`

type GetADRIngestCursorParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) GetADRIngestCursor(ctx context.Context, arg GetADRIngestCursorParams) (AdrIngestCursor, error) {
	row := q.db.QueryRow(ctx, getADRIngestCursor, arg.ScopeKind, arg.ScopeKey)
	var i AdrIngestCursor
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeKey,
		&i.LastPath,
		&i.LastChecksum,
		&i.UpdatedAt,
	)
	return i, err
}

const getADRIngestFile = `-- name: GetADRIngestFile :one
SELECT scope_kind, scope_key, relative_path, checksum, adr_id, lore_entry_id, skipped, skip_reason, processed_at
FROM adr_ingest_files
WHERE scope_kind = $1 AND scope_key = $2 AND relative_path = $3 AND checksum = $4
`

type GetADRIngestFileParams struct {
	ScopeKind    string
	ScopeKey     string
	RelativePath string
	Checksum     string
}

func (q *Queries) GetADRIngestFile(ctx context.Context, arg GetADRIngestFileParams) (AdrIngestFile, error) {
	row := q.db.QueryRow(ctx, getADRIngestFile,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.RelativePath,
		arg.Checksum,
	)
	var i AdrIngestFile
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeKey,
		&i.RelativePath,
		&i.Checksum,
		&i.AdrID,
		&i.LoreEntryID,
		&i.Skipped,
		&i.SkipReason,
		&i.ProcessedAt,
	)
	return i, err
}

const getADRIngestRun = `-- name: GetADRIngestRun :one
SELECT
    id, scope_kind, scope_key, actor_id, local_path, extra_dirs, status,
    files_seen, files_skipped, lore_stored, lore_superseded,
    error_summary, started_at, finished_at
FROM adr_ingest_runs
WHERE id = $1
`

func (q *Queries) GetADRIngestRun(ctx context.Context, id string) (AdrIngestRun, error) {
	row := q.db.QueryRow(ctx, getADRIngestRun, id)
	var i AdrIngestRun
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.ActorID,
		&i.LocalPath,
		&i.ExtraDirs,
		&i.Status,
		&i.FilesSeen,
		&i.FilesSkipped,
		&i.LoreStored,
		&i.LoreSuperseded,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertADRIngestFile = `-- name: InsertADRIngestFile :exec
INSERT INTO adr_ingest_files (
    scope_kind, scope_key, relative_path, checksum, adr_id, lore_entry_id, skipped, skip_reason, processed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertADRIngestFileParams struct {
	ScopeKind    string
	ScopeKey     string
	RelativePath string
	Checksum     string
	AdrID        pgtype.Text
	LoreEntryID  pgtype.Text
	Skipped      bool
	SkipReason   pgtype.Text
	ProcessedAt  pgtype.Timestamptz
}

func (q *Queries) InsertADRIngestFile(ctx context.Context, arg InsertADRIngestFileParams) error {
	_, err := q.db.Exec(ctx, insertADRIngestFile,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.RelativePath,
		arg.Checksum,
		arg.AdrID,
		arg.LoreEntryID,
		arg.Skipped,
		arg.SkipReason,
		arg.ProcessedAt,
	)
	return err
}

const insertADRIngestRun = `-- name: InsertADRIngestRun :exec
INSERT INTO adr_ingest_runs (
    id, scope_kind, scope_key, actor_id, local_path, extra_dirs, status,
    files_seen, files_skipped, lore_stored, lore_superseded,
    error_summary, started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14
)
`

type InsertADRIngestRunParams struct {
	ID             string
	ScopeKind      string
	ScopeKey       string
	ActorID        string
	LocalPath      string
	ExtraDirs      string
	Status         string
	FilesSeen      int32
	FilesSkipped   int32
	LoreStored     int32
	LoreSuperseded int32
	ErrorSummary   pgtype.Text
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

func (q *Queries) InsertADRIngestRun(ctx context.Context, arg InsertADRIngestRunParams) error {
	_, err := q.db.Exec(ctx, insertADRIngestRun,
		arg.ID,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.ActorID,
		arg.LocalPath,
		arg.ExtraDirs,
		arg.Status,
		arg.FilesSeen,
		arg.FilesSkipped,
		arg.LoreStored,
		arg.LoreSuperseded,
		arg.ErrorSummary,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const latestStoredADRByID = `-- name: LatestStoredADRByID :one
SELECT scope_kind, scope_key, relative_path, checksum, adr_id, lore_entry_id, skipped, skip_reason, processed_at
FROM adr_ingest_files
WHERE scope_kind = $1 AND scope_key = $2
  AND skipped = FALSE AND lore_entry_id IS NOT NULL AND lore_entry_id <> ''
  AND adr_id IS NOT NULL
  AND (
    adr_id = $3
    OR adr_id LIKE $3 || '-%'
  )
ORDER BY processed_at DESC
LIMIT 1
`

type LatestStoredADRByIDParams struct {
	ScopeKind string
	ScopeKey  string
	AdrID     pgtype.Text
}

func (q *Queries) LatestStoredADRByID(ctx context.Context, arg LatestStoredADRByIDParams) (AdrIngestFile, error) {
	row := q.db.QueryRow(ctx, latestStoredADRByID, arg.ScopeKind, arg.ScopeKey, arg.AdrID)
	var i AdrIngestFile
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeKey,
		&i.RelativePath,
		&i.Checksum,
		&i.AdrID,
		&i.LoreEntryID,
		&i.Skipped,
		&i.SkipReason,
		&i.ProcessedAt,
	)
	return i, err
}

const latestStoredADRByPath = `-- name: LatestStoredADRByPath :one
SELECT scope_kind, scope_key, relative_path, checksum, adr_id, lore_entry_id, skipped, skip_reason, processed_at
FROM adr_ingest_files
WHERE scope_kind = $1 AND scope_key = $2 AND relative_path = $3
  AND skipped = FALSE AND lore_entry_id IS NOT NULL AND lore_entry_id <> ''
ORDER BY processed_at DESC
LIMIT 1
`

type LatestStoredADRByPathParams struct {
	ScopeKind    string
	ScopeKey     string
	RelativePath string
}

func (q *Queries) LatestStoredADRByPath(ctx context.Context, arg LatestStoredADRByPathParams) (AdrIngestFile, error) {
	row := q.db.QueryRow(ctx, latestStoredADRByPath, arg.ScopeKind, arg.ScopeKey, arg.RelativePath)
	var i AdrIngestFile
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeKey,
		&i.RelativePath,
		&i.Checksum,
		&i.AdrID,
		&i.LoreEntryID,
		&i.Skipped,
		&i.SkipReason,
		&i.ProcessedAt,
	)
	return i, err
}

const listADRIngestRunsByScope = `-- name: ListADRIngestRunsByScope :many
SELECT
    id, scope_kind, scope_key, actor_id, local_path, extra_dirs, status,
    files_seen, files_skipped, lore_stored, lore_superseded,
    error_summary, started_at, finished_at
FROM adr_ingest_runs
WHERE scope_kind = $1 AND scope_key = $2
ORDER BY started_at DESC
`

type ListADRIngestRunsByScopeParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) ListADRIngestRunsByScope(ctx context.Context, arg ListADRIngestRunsByScopeParams) ([]AdrIngestRun, error) {
	rows, err := q.db.Query(ctx, listADRIngestRunsByScope, arg.ScopeKind, arg.ScopeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdrIngestRun{}
	for rows.Next() {
		var i AdrIngestRun
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeKey,
			&i.ActorID,
			&i.LocalPath,
			&i.ExtraDirs,
			&i.Status,
			&i.FilesSeen,
			&i.FilesSkipped,
			&i.LoreStored,
			&i.LoreSuperseded,
			&i.ErrorSummary,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateADRIngestRun = `-- name: UpdateADRIngestRun :exec
UPDATE adr_ingest_runs SET
    status = $2,
    files_seen = $3,
    files_skipped = $4,
    lore_stored = $5,
    lore_superseded = $6,
    error_summary = $7,
    finished_at = $8
WHERE id = $1
`

type UpdateADRIngestRunParams struct {
	ID             string
	Status         string
	FilesSeen      int32
	FilesSkipped   int32
	LoreStored     int32
	LoreSuperseded int32
	ErrorSummary   pgtype.Text
	FinishedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateADRIngestRun(ctx context.Context, arg UpdateADRIngestRunParams) error {
	_, err := q.db.Exec(ctx, updateADRIngestRun,
		arg.ID,
		arg.Status,
		arg.FilesSeen,
		arg.FilesSkipped,
		arg.LoreStored,
		arg.LoreSuperseded,
		arg.ErrorSummary,
		arg.FinishedAt,
	)
	return err
}

const upsertADRIngestCursor = `-- name: UpsertADRIngestCursor :exec
INSERT INTO adr_ingest_cursors (scope_kind, scope_key, last_path, last_checksum, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scope_kind, scope_key) DO UPDATE SET
    last_path = EXCLUDED.last_path,
    last_checksum = EXCLUDED.last_checksum,
    updated_at = EXCLUDED.updated_at
`

type UpsertADRIngestCursorParams struct {
	ScopeKind    string
	ScopeKey     string
	LastPath     pgtype.Text
	LastChecksum pgtype.Text
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertADRIngestCursor(ctx context.Context, arg UpsertADRIngestCursorParams) error {
	_, err := q.db.Exec(ctx, upsertADRIngestCursor,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.LastPath,
		arg.LastChecksum,
		arg.UpdatedAt,
	)
	return err
}
