// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditRecord = `-- name: InsertAuditRecord :exec
INSERT INTO audit_records (id, target_id, action, actor_id, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditRecordParams struct {
	ID        string
	TargetID  string
	Action    string
	ActorID   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertAuditRecord(ctx context.Context, arg InsertAuditRecordParams) error {
	_, err := q.db.Exec(ctx, insertAuditRecord,
		arg.ID,
		arg.TargetID,
		arg.Action,
		arg.ActorID,
		arg.CreatedAt,
	)
	return err
}

const listAuditRecordsByTarget = `-- name: ListAuditRecordsByTarget :many
SELECT id, target_id, action, actor_id, created_at
FROM audit_records
WHERE target_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAuditRecordsByTarget(ctx context.Context, targetID string) ([]AuditRecord, error) {
	rows, err := q.db.Query(ctx, listAuditRecordsByTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Action,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
