// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: decisions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDecision = `-- name: InsertDecision :exec
INSERT INTO decisions (
    id, scope_kind, scope_key, question, choice, rationale, consequences,
    owner, decided_at, source_kind, superseded_by_id, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14
)
`

type InsertDecisionParams struct {
	ID             string
	ScopeKind      string
	ScopeKey       string
	Question       string
	Choice         string
	Rationale      string
	Consequences   string
	Owner          string
	DecidedAt      pgtype.Timestamptz
	SourceKind     string
	SupersededByID pgtype.Text
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) error {
	_, err := q.db.Exec(ctx, insertDecision,
		arg.ID,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.Question,
		arg.Choice,
		arg.Rationale,
		arg.Consequences,
		arg.Owner,
		arg.DecidedAt,
		arg.SourceKind,
		arg.SupersededByID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getDecision = `-- name: GetDecision :one
SELECT
    id, scope_kind, scope_key, question, choice, rationale, consequences,
    owner, decided_at, source_kind, superseded_by_id, created_by, created_at, updated_at
FROM decisions
WHERE id = $1
`

func (q *Queries) GetDecision(ctx context.Context, id string) (Decision, error) {
	row := q.db.QueryRow(ctx, getDecision, id)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.Question,
		&i.Choice,
		&i.Rationale,
		&i.Consequences,
		&i.Owner,
		&i.DecidedAt,
		&i.SourceKind,
		&i.SupersededByID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDecision = `-- name: UpdateDecision :exec
UPDATE decisions SET
    question = $2,
    choice = $3,
    rationale = $4,
    consequences = $5,
    owner = $6,
    decided_at = $7,
    source_kind = $8,
    superseded_by_id = $9,
    updated_at = $10
WHERE id = $1
`

type UpdateDecisionParams struct {
	ID             string
	Question       string
	Choice         string
	Rationale      string
	Consequences   string
	Owner          string
	DecidedAt      pgtype.Timestamptz
	SourceKind     string
	SupersededByID pgtype.Text
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateDecision(ctx context.Context, arg UpdateDecisionParams) error {
	_, err := q.db.Exec(ctx, updateDecision,
		arg.ID,
		arg.Question,
		arg.Choice,
		arg.Rationale,
		arg.Consequences,
		arg.Owner,
		arg.DecidedAt,
		arg.SourceKind,
		arg.SupersededByID,
		arg.UpdatedAt,
	)
	return err
}

const listDecisionsByScope = `-- name: ListDecisionsByScope :many
SELECT
    id, scope_kind, scope_key, question, choice, rationale, consequences,
    owner, decided_at, source_kind, superseded_by_id, created_by, created_at, updated_at
FROM decisions
WHERE scope_kind = $1 AND scope_key = $2
ORDER BY decided_at DESC
`

type ListDecisionsByScopeParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) ListDecisionsByScope(ctx context.Context, arg ListDecisionsByScopeParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByScope, arg.ScopeKind, arg.ScopeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeKey,
			&i.Question,
			&i.Choice,
			&i.Rationale,
			&i.Consequences,
			&i.Owner,
			&i.DecidedAt,
			&i.SourceKind,
			&i.SupersededByID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDecisionAlternative = `-- name: InsertDecisionAlternative :exec
INSERT INTO decision_alternatives (decision_id, position, label, note)
VALUES ($1, $2, $3, $4)
`

type InsertDecisionAlternativeParams struct {
	DecisionID string
	Position   int32
	Label      string
	Note       string
}

func (q *Queries) InsertDecisionAlternative(ctx context.Context, arg InsertDecisionAlternativeParams) error {
	_, err := q.db.Exec(ctx, insertDecisionAlternative, arg.DecisionID, arg.Position, arg.Label, arg.Note)
	return err
}

const deleteDecisionAlternatives = `-- name: DeleteDecisionAlternatives :exec
DELETE FROM decision_alternatives WHERE decision_id = $1
`

func (q *Queries) DeleteDecisionAlternatives(ctx context.Context, decisionID string) error {
	_, err := q.db.Exec(ctx, deleteDecisionAlternatives, decisionID)
	return err
}

const listDecisionAlternatives = `-- name: ListDecisionAlternatives :many
SELECT decision_id, position, label, note
FROM decision_alternatives
WHERE decision_id = $1
ORDER BY position ASC
`

func (q *Queries) ListDecisionAlternatives(ctx context.Context, decisionID string) ([]DecisionAlternative, error) {
	rows, err := q.db.Query(ctx, listDecisionAlternatives, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DecisionAlternative{}
	for rows.Next() {
		var i DecisionAlternative
		if err := rows.Scan(&i.DecisionID, &i.Position, &i.Label, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDecisionComponent = `-- name: InsertDecisionComponent :exec
INSERT INTO decision_components (decision_id, position, name)
VALUES ($1, $2, $3)
`

type InsertDecisionComponentParams struct {
	DecisionID string
	Position   int32
	Name       string
}

func (q *Queries) InsertDecisionComponent(ctx context.Context, arg InsertDecisionComponentParams) error {
	_, err := q.db.Exec(ctx, insertDecisionComponent, arg.DecisionID, arg.Position, arg.Name)
	return err
}

const deleteDecisionComponents = `-- name: DeleteDecisionComponents :exec
DELETE FROM decision_components WHERE decision_id = $1
`

func (q *Queries) DeleteDecisionComponents(ctx context.Context, decisionID string) error {
	_, err := q.db.Exec(ctx, deleteDecisionComponents, decisionID)
	return err
}

const listDecisionComponents = `-- name: ListDecisionComponents :many
SELECT decision_id, position, name
FROM decision_components
WHERE decision_id = $1
ORDER BY position ASC
`

func (q *Queries) ListDecisionComponents(ctx context.Context, decisionID string) ([]DecisionComponent, error) {
	rows, err := q.db.Query(ctx, listDecisionComponents, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DecisionComponent{}
	for rows.Next() {
		var i DecisionComponent
		if err := rows.Scan(&i.DecisionID, &i.Position, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
