// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ingest.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGitIngestCursor = `-- name: GetGitIngestCursor :one
SELECT scope_kind, scope_key, last_sha, last_committed_at, updated_at
FROM git_ingest_cursors
WHERE scope_kind = $1 AND scope_key = $2
`

type GetGitIngestCursorParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) GetGitIngestCursor(ctx context.Context, arg GetGitIngestCursorParams) (GitIngestCursor, error) {
	row := q.db.QueryRow(ctx, getGitIngestCursor, arg.ScopeKind, arg.ScopeKey)
	var i GitIngestCursor
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeKey,
		&i.LastSha,
		&i.LastCommittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitIngestRun = `-- name: GetGitIngestRun :one
SELECT
    id, scope_kind, scope_key, actor_id, local_path, status,
    commits_seen, commits_skipped, candidates_stored,
    cursor_sha, cursor_at, error_summary, started_at, finished_at
FROM git_ingest_runs
WHERE id = $1
`

func (q *Queries) GetGitIngestRun(ctx context.Context, id string) (GitIngestRun, error) {
	row := q.db.QueryRow(ctx, getGitIngestRun, id)
	var i GitIngestRun
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.ActorID,
		&i.LocalPath,
		&i.Status,
		&i.CommitsSeen,
		&i.CommitsSkipped,
		&i.CandidatesStored,
		&i.CursorSha,
		&i.CursorAt,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGitIngestSHA = `-- name: GetGitIngestSHA :one
SELECT scope_kind, scope_key, sha, lore_entry_id, skipped, skip_reason, processed_at
FROM git_ingest_shas
WHERE scope_kind = $1 AND scope_key = $2 AND sha = $3
`

type GetGitIngestSHAParams struct {
	ScopeKind string
	ScopeKey  string
	Sha       string
}

func (q *Queries) GetGitIngestSHA(ctx context.Context, arg GetGitIngestSHAParams) (GitIngestSha, error) {
	row := q.db.QueryRow(ctx, getGitIngestSHA, arg.ScopeKind, arg.ScopeKey, arg.Sha)
	var i GitIngestSha
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeKey,
		&i.Sha,
		&i.LoreEntryID,
		&i.Skipped,
		&i.SkipReason,
		&i.ProcessedAt,
	)
	return i, err
}

const insertGitIngestRun = `-- name: InsertGitIngestRun :exec
INSERT INTO git_ingest_runs (
    id, scope_kind, scope_key, actor_id, local_path, status,
    commits_seen, commits_skipped, candidates_stored,
    cursor_sha, cursor_at, error_summary, started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14
)
`

type InsertGitIngestRunParams struct {
	ID               string
	ScopeKind        string
	ScopeKey         string
	ActorID          string
	LocalPath        string
	Status           string
	CommitsSeen      int32
	CommitsSkipped   int32
	CandidatesStored int32
	CursorSha        pgtype.Text
	CursorAt         pgtype.Timestamptz
	ErrorSummary     pgtype.Text
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
}

func (q *Queries) InsertGitIngestRun(ctx context.Context, arg InsertGitIngestRunParams) error {
	_, err := q.db.Exec(ctx, insertGitIngestRun,
		arg.ID,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.ActorID,
		arg.LocalPath,
		arg.Status,
		arg.CommitsSeen,
		arg.CommitsSkipped,
		arg.CandidatesStored,
		arg.CursorSha,
		arg.CursorAt,
		arg.ErrorSummary,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const insertGitIngestSHA = `-- name: InsertGitIngestSHA :exec
INSERT INTO git_ingest_shas (
    scope_kind, scope_key, sha, lore_entry_id, skipped, skip_reason, processed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertGitIngestSHAParams struct {
	ScopeKind   string
	ScopeKey    string
	Sha         string
	LoreEntryID pgtype.Text
	Skipped     bool
	SkipReason  pgtype.Text
	ProcessedAt pgtype.Timestamptz
}

func (q *Queries) InsertGitIngestSHA(ctx context.Context, arg InsertGitIngestSHAParams) error {
	_, err := q.db.Exec(ctx, insertGitIngestSHA,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.Sha,
		arg.LoreEntryID,
		arg.Skipped,
		arg.SkipReason,
		arg.ProcessedAt,
	)
	return err
}

const listGitIngestRunsByScope = `-- name: ListGitIngestRunsByScope :many
SELECT
    id, scope_kind, scope_key, actor_id, local_path, status,
    commits_seen, commits_skipped, candidates_stored,
    cursor_sha, cursor_at, error_summary, started_at, finished_at
FROM git_ingest_runs
WHERE scope_kind = $1 AND scope_key = $2
ORDER BY started_at DESC
`

type ListGitIngestRunsByScopeParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) ListGitIngestRunsByScope(ctx context.Context, arg ListGitIngestRunsByScopeParams) ([]GitIngestRun, error) {
	rows, err := q.db.Query(ctx, listGitIngestRunsByScope, arg.ScopeKind, arg.ScopeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitIngestRun{}
	for rows.Next() {
		var i GitIngestRun
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeKey,
			&i.ActorID,
			&i.LocalPath,
			&i.Status,
			&i.CommitsSeen,
			&i.CommitsSkipped,
			&i.CandidatesStored,
			&i.CursorSha,
			&i.CursorAt,
			&i.ErrorSummary,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitIngestRun = `-- name: UpdateGitIngestRun :exec
UPDATE git_ingest_runs SET
    status = $2,
    commits_seen = $3,
    commits_skipped = $4,
    candidates_stored = $5,
    cursor_sha = $6,
    cursor_at = $7,
    error_summary = $8,
    finished_at = $9
WHERE id = $1
`

type UpdateGitIngestRunParams struct {
	ID               string
	Status           string
	CommitsSeen      int32
	CommitsSkipped   int32
	CandidatesStored int32
	CursorSha        pgtype.Text
	CursorAt         pgtype.Timestamptz
	ErrorSummary     pgtype.Text
	FinishedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateGitIngestRun(ctx context.Context, arg UpdateGitIngestRunParams) error {
	_, err := q.db.Exec(ctx, updateGitIngestRun,
		arg.ID,
		arg.Status,
		arg.CommitsSeen,
		arg.CommitsSkipped,
		arg.CandidatesStored,
		arg.CursorSha,
		arg.CursorAt,
		arg.ErrorSummary,
		arg.FinishedAt,
	)
	return err
}

const upsertGitIngestCursor = `-- name: UpsertGitIngestCursor :exec
INSERT INTO git_ingest_cursors (scope_kind, scope_key, last_sha, last_committed_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scope_kind, scope_key) DO UPDATE SET
    last_sha = EXCLUDED.last_sha,
    last_committed_at = EXCLUDED.last_committed_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertGitIngestCursorParams struct {
	ScopeKind       string
	ScopeKey        string
	LastSha         string
	LastCommittedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertGitIngestCursor(ctx context.Context, arg UpsertGitIngestCursorParams) error {
	_, err := q.db.Exec(ctx, upsertGitIngestCursor,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.LastSha,
		arg.LastCommittedAt,
		arg.UpdatedAt,
	)
	return err
}
