// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: lore.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLoreEntry = `-- name: GetLoreEntry :one
SELECT
    id, statement, scope_kind, scope_key, origin, verification_status,
    evidence, created_by, created_at, verified_by, verified_at, updated_at,
    superseded_by_id, invalidated_by, invalidated_at
FROM lore_entries
WHERE id = $1
`

func (q *Queries) GetLoreEntry(ctx context.Context, id string) (LoreEntry, error) {
	row := q.db.QueryRow(ctx, getLoreEntry, id)
	var i LoreEntry
	err := row.Scan(
		&i.ID,
		&i.Statement,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.Origin,
		&i.VerificationStatus,
		&i.Evidence,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.UpdatedAt,
		&i.SupersededByID,
		&i.InvalidatedBy,
		&i.InvalidatedAt,
	)
	return i, err
}

const insertLoreEntry = `-- name: InsertLoreEntry :exec
INSERT INTO lore_entries (
    id, statement, scope_kind, scope_key, origin, verification_status,
    evidence, created_by, created_at, verified_by, verified_at, updated_at,
    superseded_by_id, invalidated_by, invalidated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
`

type InsertLoreEntryParams struct {
	ID                 string
	Statement          string
	ScopeKind          string
	ScopeKey           string
	Origin             string
	VerificationStatus string
	Evidence           []byte
	CreatedBy          string
	CreatedAt          pgtype.Timestamptz
	VerifiedBy         pgtype.Text
	VerifiedAt         pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	SupersededByID     pgtype.Text
	InvalidatedBy      pgtype.Text
	InvalidatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertLoreEntry(ctx context.Context, arg InsertLoreEntryParams) error {
	_, err := q.db.Exec(ctx, insertLoreEntry,
		arg.ID,
		arg.Statement,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.Origin,
		arg.VerificationStatus,
		arg.Evidence,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.VerifiedBy,
		arg.VerifiedAt,
		arg.UpdatedAt,
		arg.SupersededByID,
		arg.InvalidatedBy,
		arg.InvalidatedAt,
	)
	return err
}

const listLoreEntriesByScope = `-- name: ListLoreEntriesByScope :many
SELECT
    id, statement, scope_kind, scope_key, origin, verification_status,
    evidence, created_by, created_at, verified_by, verified_at, updated_at,
    superseded_by_id, invalidated_by, invalidated_at
FROM lore_entries
WHERE scope_kind = $1 AND scope_key = $2
ORDER BY created_at DESC
`

type ListLoreEntriesByScopeParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) ListLoreEntriesByScope(ctx context.Context, arg ListLoreEntriesByScopeParams) ([]LoreEntry, error) {
	rows, err := q.db.Query(ctx, listLoreEntriesByScope, arg.ScopeKind, arg.ScopeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoreEntry{}
	for rows.Next() {
		var i LoreEntry
		if err := rows.Scan(
			&i.ID,
			&i.Statement,
			&i.ScopeKind,
			&i.ScopeKey,
			&i.Origin,
			&i.VerificationStatus,
			&i.Evidence,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.UpdatedAt,
			&i.SupersededByID,
			&i.InvalidatedBy,
			&i.InvalidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoreEntry = `-- name: UpdateLoreEntry :exec
UPDATE lore_entries SET
    statement = $2,
    scope_kind = $3,
    scope_key = $4,
    origin = $5,
    verification_status = $6,
    evidence = $7,
    created_by = $8,
    created_at = $9,
    verified_by = $10,
    verified_at = $11,
    updated_at = $12,
    superseded_by_id = $13,
    invalidated_by = $14,
    invalidated_at = $15
WHERE id = $1
`

type UpdateLoreEntryParams struct {
	ID                 string
	Statement          string
	ScopeKind          string
	ScopeKey           string
	Origin             string
	VerificationStatus string
	Evidence           []byte
	CreatedBy          string
	CreatedAt          pgtype.Timestamptz
	VerifiedBy         pgtype.Text
	VerifiedAt         pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	SupersededByID     pgtype.Text
	InvalidatedBy      pgtype.Text
	InvalidatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateLoreEntry(ctx context.Context, arg UpdateLoreEntryParams) error {
	_, err := q.db.Exec(ctx, updateLoreEntry,
		arg.ID,
		arg.Statement,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.Origin,
		arg.VerificationStatus,
		arg.Evidence,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.VerifiedBy,
		arg.VerifiedAt,
		arg.UpdatedAt,
		arg.SupersededByID,
		arg.InvalidatedBy,
		arg.InvalidatedAt,
	)
	return err
}
