// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: membership.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE user_id = $1 AND target_kind = $2 AND target_id = $3
`

type DeleteMembershipParams struct {
	UserID     string
	TargetKind string
	TargetID   string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.TargetKind, arg.TargetID)
	return err
}

const deleteScopeBinding = `-- name: DeleteScopeBinding :exec
DELETE FROM scope_bindings WHERE scope_kind = $1 AND scope_key = $2
`

type DeleteScopeBindingParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) DeleteScopeBinding(ctx context.Context, arg DeleteScopeBindingParams) error {
	_, err := q.db.Exec(ctx, deleteScopeBinding, arg.ScopeKind, arg.ScopeKey)
	return err
}

const ensureUser = `-- name: EnsureUser :one
INSERT INTO users (id, subject, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (subject) DO UPDATE SET subject = EXCLUDED.subject
RETURNING id, subject, created_at
`

type EnsureUserParams struct {
	ID        string
	Subject   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureUser, arg.ID, arg.Subject, arg.CreatedAt)
	var i User
	err := row.Scan(&i.ID, &i.Subject, &i.CreatedAt)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, key, name, team_id, created_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, key, name, team_id, created_at FROM projects WHERE key = $1
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const getScopeBinding = `-- name: GetScopeBinding :one
SELECT id, scope_kind, scope_key, project_id, created_at
FROM scope_bindings
WHERE scope_kind = $1 AND scope_key = $2
`

type GetScopeBindingParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) GetScopeBinding(ctx context.Context, arg GetScopeBindingParams) (ScopeBinding, error) {
	row := q.db.QueryRow(ctx, getScopeBinding, arg.ScopeKind, arg.ScopeKey)
	var i ScopeBinding
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.ProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByKey = `-- name: GetTeamByKey :one
SELECT id, key, name, created_at FROM teams WHERE key = $1
`

func (q *Queries) GetTeamByKey(ctx context.Context, key string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByKey, key)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamKeyByID = `-- name: GetTeamKeyByID :one
SELECT key FROM teams WHERE id = $1
`

func (q *Queries) GetTeamKeyByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTeamKeyByID, id)
	var key string
	err := row.Scan(&key)
	return key, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, subject, created_at FROM users WHERE subject = $1
`

func (q *Queries) GetUserBySubject(ctx context.Context, subject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubject, subject)
	var i User
	err := row.Scan(&i.ID, &i.Subject, &i.CreatedAt)
	return i, err
}

const hasMembership = `-- name: HasMembership :one
SELECT EXISTS(
    SELECT 1 FROM memberships
    WHERE user_id = $1 AND target_kind = $2 AND target_id = $3
) AS ok
`

type HasMembershipParams struct {
	UserID     string
	TargetKind string
	TargetID   string
}

func (q *Queries) HasMembership(ctx context.Context, arg HasMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMembership, arg.UserID, arg.TargetKind, arg.TargetID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO memberships (id, user_id, target_kind, target_id, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertMembershipParams struct {
	ID         string
	UserID     string
	TargetKind string
	TargetID   string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.Exec(ctx, insertMembership,
		arg.ID,
		arg.UserID,
		arg.TargetKind,
		arg.TargetID,
		arg.CreatedAt,
	)
	return err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO projects (id, key, name, team_id, created_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertProjectParams struct {
	ID        string
	Key       string
	Name      string
	TeamID    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.Exec(ctx, insertProject,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.TeamID,
		arg.CreatedAt,
	)
	return err
}

const insertScopeBinding = `-- name: InsertScopeBinding :exec
INSERT INTO scope_bindings (id, scope_kind, scope_key, project_id, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertScopeBindingParams struct {
	ID        string
	ScopeKind string
	ScopeKey  string
	ProjectID string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertScopeBinding(ctx context.Context, arg InsertScopeBindingParams) error {
	_, err := q.db.Exec(ctx, insertScopeBinding,
		arg.ID,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.ProjectID,
		arg.CreatedAt,
	)
	return err
}

const insertTeam = `-- name: InsertTeam :exec
INSERT INTO teams (id, key, name, created_at) VALUES ($1, $2, $3, $4)
`

type InsertTeamParams struct {
	ID        string
	Key       string
	Name      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) error {
	_, err := q.db.Exec(ctx, insertTeam,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}
