// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditRecord struct {
	ID        string
	TargetID  string
	Action    string
	ActorID   string
	CreatedAt pgtype.Timestamptz
}

type GitIngestCursor struct {
	ScopeKind       string
	ScopeKey        string
	LastSha         string
	LastCommittedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type GitIngestRun struct {
	ID               string
	ScopeKind        string
	ScopeKey         string
	ActorID          string
	LocalPath        string
	Status           string
	CommitsSeen      int32
	CommitsSkipped   int32
	CandidatesStored int32
	CursorSha        pgtype.Text
	CursorAt         pgtype.Timestamptz
	ErrorSummary     pgtype.Text
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
}

type GitIngestSha struct {
	ScopeKind   string
	ScopeKey    string
	Sha         string
	LoreEntryID pgtype.Text
	Skipped     bool
	SkipReason  pgtype.Text
	ProcessedAt pgtype.Timestamptz
}

type LoreEntry struct {
	ID                 string
	Statement          string
	ScopeKind          string
	ScopeKey           string
	Origin             string
	VerificationStatus string
	Evidence           []byte
	CreatedBy          string
	CreatedAt          pgtype.Timestamptz
	VerifiedBy         pgtype.Text
	VerifiedAt         pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	SupersededByID     pgtype.Text
	InvalidatedBy      pgtype.Text
	InvalidatedAt      pgtype.Timestamptz
}

type Membership struct {
	ID         string
	UserID     string
	TargetKind string
	TargetID   string
	CreatedAt  pgtype.Timestamptz
}

type OutboxEvent struct {
	ID             string
	AggregateType  string
	AggregateID    string
	EventType      string
	Payload        []byte
	Status         string
	Attempts       int32
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	ProcessedAt    pgtype.Timestamptz
	LastError      pgtype.Text
}

type Project struct {
	ID        string
	Key       string
	Name      string
	TeamID    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type ScopeBinding struct {
	ID        string
	ScopeKind string
	ScopeKey  string
	ProjectID string
	CreatedAt pgtype.Timestamptz
}

type Team struct {
	ID        string
	Key       string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        string
	Subject   string
	CreatedAt pgtype.Timestamptz
}
