// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"encoding/json"
	"time"
)

type AuditRecord struct {
	ID        string
	TargetID  string
	Action    string
	ActorID   string
	CreatedAt time.Time
}

type LoreEntry struct {
	ID                 string
	Statement          string
	ScopeKind          string
	ScopeKey           string
	Origin             string
	VerificationStatus string
	Evidence           json.RawMessage
	CreatedBy          string
	CreatedAt          time.Time
	VerifiedBy         *string
	VerifiedAt         *time.Time
	UpdatedAt          time.Time
}
