// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditRecord struct {
	ID        string
	TargetID  string
	Action    string
	ActorID   string
	CreatedAt pgtype.Timestamptz
}

type LoreEntry struct {
	ID                 string
	Statement          string
	ScopeKind          string
	ScopeKey           string
	Origin             string
	VerificationStatus string
	Evidence           []byte
	CreatedBy          string
	CreatedAt          pgtype.Timestamptz
	VerifiedBy         pgtype.Text
	VerifiedAt         pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
