// Code generated by sqlc. DO NOT EDIT.
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    id,
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    status,
    attempts,
    idempotency_key,
    created_at,
    processed_at,
    last_error
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertOutboxEventParams struct {
	ID             string
	AggregateType  string
	AggregateID    string
	EventType      string
	Payload        []byte
	Status         string
	Attempts       int32
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	ProcessedAt    pgtype.Timestamptz
	LastError      pgtype.Text
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.ProcessedAt,
		arg.LastError,
	)
	return err
}

const claimPendingOutboxEvents = `-- name: ClaimPendingOutboxEvents :many
SELECT
    id,
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    status,
    attempts,
    idempotency_key,
    created_at,
    processed_at,
    last_error
FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventCompleted = `-- name: MarkOutboxEventCompleted :exec
UPDATE outbox_events
SET status = 'completed',
    processed_at = $2,
    last_error = NULL
WHERE id = $1
`

type MarkOutboxEventCompletedParams struct {
	ID          string
	ProcessedAt pgtype.Timestamptz
}

func (q *Queries) MarkOutboxEventCompleted(ctx context.Context, arg MarkOutboxEventCompletedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventCompleted, arg.ID, arg.ProcessedAt)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET status = 'pending',
    attempts = $2,
    last_error = $3
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID        string
	Attempts  int32
	LastError pgtype.Text
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.Attempts, arg.LastError)
	return err
}
