// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pr_ingest.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPRIngestCursor = `-- name: GetPRIngestCursor :one
SELECT scope_kind, scope_key, last_pr, last_merged_at, updated_at
FROM pr_ingest_cursors
WHERE scope_kind = $1 AND scope_key = $2
`

type GetPRIngestCursorParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) GetPRIngestCursor(ctx context.Context, arg GetPRIngestCursorParams) (PrIngestCursor, error) {
	row := q.db.QueryRow(ctx, getPRIngestCursor, arg.ScopeKind, arg.ScopeKey)
	var i PrIngestCursor
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeKey,
		&i.LastPr,
		&i.LastMergedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPRIngestPR = `-- name: GetPRIngestPR :one
SELECT scope_kind, scope_key, pr_number, node_id, lore_entry_id, skipped, skip_reason, processed_at
FROM pr_ingest_prs
WHERE scope_kind = $1 AND scope_key = $2 AND pr_number = $3
`

type GetPRIngestPRParams struct {
	ScopeKind string
	ScopeKey  string
	PrNumber  int32
}

func (q *Queries) GetPRIngestPR(ctx context.Context, arg GetPRIngestPRParams) (PrIngestPr, error) {
	row := q.db.QueryRow(ctx, getPRIngestPR, arg.ScopeKind, arg.ScopeKey, arg.PrNumber)
	var i PrIngestPr
	err := row.Scan(
		&i.ScopeKind,
		&i.ScopeKey,
		&i.PrNumber,
		&i.NodeID,
		&i.LoreEntryID,
		&i.Skipped,
		&i.SkipReason,
		&i.ProcessedAt,
	)
	return i, err
}

const getPRIngestRun = `-- name: GetPRIngestRun :one
SELECT
    id, scope_kind, scope_key, actor_id, pr_number, status,
    prs_seen, prs_skipped, candidates_stored,
    cursor_pr, cursor_at, error_summary, started_at, finished_at
FROM pr_ingest_runs
WHERE id = $1
`

func (q *Queries) GetPRIngestRun(ctx context.Context, id string) (PrIngestRun, error) {
	row := q.db.QueryRow(ctx, getPRIngestRun, id)
	var i PrIngestRun
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.ActorID,
		&i.PrNumber,
		&i.Status,
		&i.PrsSeen,
		&i.PrsSkipped,
		&i.CandidatesStored,
		&i.CursorPr,
		&i.CursorAt,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertPRIngestPR = `-- name: InsertPRIngestPR :exec
INSERT INTO pr_ingest_prs (
    scope_kind, scope_key, pr_number, node_id, lore_entry_id, skipped, skip_reason, processed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPRIngestPRParams struct {
	ScopeKind   string
	ScopeKey    string
	PrNumber    int32
	NodeID      pgtype.Text
	LoreEntryID pgtype.Text
	Skipped     bool
	SkipReason  pgtype.Text
	ProcessedAt pgtype.Timestamptz
}

func (q *Queries) InsertPRIngestPR(ctx context.Context, arg InsertPRIngestPRParams) error {
	_, err := q.db.Exec(ctx, insertPRIngestPR,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.PrNumber,
		arg.NodeID,
		arg.LoreEntryID,
		arg.Skipped,
		arg.SkipReason,
		arg.ProcessedAt,
	)
	return err
}

const insertPRIngestRun = `-- name: InsertPRIngestRun :exec
INSERT INTO pr_ingest_runs (
    id, scope_kind, scope_key, actor_id, pr_number, status,
    prs_seen, prs_skipped, candidates_stored,
    cursor_pr, cursor_at, error_summary, started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14
)
`

type InsertPRIngestRunParams struct {
	ID               string
	ScopeKind        string
	ScopeKey         string
	ActorID          string
	PrNumber         int32
	Status           string
	PrsSeen          int32
	PrsSkipped       int32
	CandidatesStored int32
	CursorPr         pgtype.Int4
	CursorAt         pgtype.Timestamptz
	ErrorSummary     pgtype.Text
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
}

func (q *Queries) InsertPRIngestRun(ctx context.Context, arg InsertPRIngestRunParams) error {
	_, err := q.db.Exec(ctx, insertPRIngestRun,
		arg.ID,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.ActorID,
		arg.PrNumber,
		arg.Status,
		arg.PrsSeen,
		arg.PrsSkipped,
		arg.CandidatesStored,
		arg.CursorPr,
		arg.CursorAt,
		arg.ErrorSummary,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const listPRIngestRunsByScope = `-- name: ListPRIngestRunsByScope :many
SELECT
    id, scope_kind, scope_key, actor_id, pr_number, status,
    prs_seen, prs_skipped, candidates_stored,
    cursor_pr, cursor_at, error_summary, started_at, finished_at
FROM pr_ingest_runs
WHERE scope_kind = $1 AND scope_key = $2
ORDER BY started_at DESC
`

type ListPRIngestRunsByScopeParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) ListPRIngestRunsByScope(ctx context.Context, arg ListPRIngestRunsByScopeParams) ([]PrIngestRun, error) {
	rows, err := q.db.Query(ctx, listPRIngestRunsByScope, arg.ScopeKind, arg.ScopeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrIngestRun{}
	for rows.Next() {
		var i PrIngestRun
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeKey,
			&i.ActorID,
			&i.PrNumber,
			&i.Status,
			&i.PrsSeen,
			&i.PrsSkipped,
			&i.CandidatesStored,
			&i.CursorPr,
			&i.CursorAt,
			&i.ErrorSummary,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePRIngestRun = `-- name: UpdatePRIngestRun :exec
UPDATE pr_ingest_runs SET
    status = $2,
    prs_seen = $3,
    prs_skipped = $4,
    candidates_stored = $5,
    cursor_pr = $6,
    cursor_at = $7,
    error_summary = $8,
    finished_at = $9
WHERE id = $1
`

type UpdatePRIngestRunParams struct {
	ID               string
	Status           string
	PrsSeen          int32
	PrsSkipped       int32
	CandidatesStored int32
	CursorPr         pgtype.Int4
	CursorAt         pgtype.Timestamptz
	ErrorSummary     pgtype.Text
	FinishedAt       pgtype.Timestamptz
}

func (q *Queries) UpdatePRIngestRun(ctx context.Context, arg UpdatePRIngestRunParams) error {
	_, err := q.db.Exec(ctx, updatePRIngestRun,
		arg.ID,
		arg.Status,
		arg.PrsSeen,
		arg.PrsSkipped,
		arg.CandidatesStored,
		arg.CursorPr,
		arg.CursorAt,
		arg.ErrorSummary,
		arg.FinishedAt,
	)
	return err
}

const upsertPRIngestCursor = `-- name: UpsertPRIngestCursor :exec
INSERT INTO pr_ingest_cursors (scope_kind, scope_key, last_pr, last_merged_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scope_kind, scope_key) DO UPDATE SET
    last_pr = EXCLUDED.last_pr,
    last_merged_at = EXCLUDED.last_merged_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertPRIngestCursorParams struct {
	ScopeKind    string
	ScopeKey     string
	LastPr       int32
	LastMergedAt pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertPRIngestCursor(ctx context.Context, arg UpsertPRIngestCursorParams) error {
	_, err := q.db.Exec(ctx, upsertPRIngestCursor,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.LastPr,
		arg.LastMergedAt,
		arg.UpdatedAt,
	)
	return err
}
