// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: review.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLoreReviewDecision = `-- name: InsertLoreReviewDecision :exec
INSERT INTO lore_review_decisions (
    id, scope_kind, scope_key, evidence_type, evidence_value, statement_checksum,
    lore_entry_id, successor_lore_id, status, actor_id, decided_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
`

type InsertLoreReviewDecisionParams struct {
	ID                string
	ScopeKind         string
	ScopeKey          string
	EvidenceType      string
	EvidenceValue     string
	StatementChecksum string
	LoreEntryID       string
	SuccessorLoreID   pgtype.Text
	Status            string
	ActorID           string
	DecidedAt         pgtype.Timestamptz
}

func (q *Queries) InsertLoreReviewDecision(ctx context.Context, arg InsertLoreReviewDecisionParams) error {
	_, err := q.db.Exec(ctx, insertLoreReviewDecision,
		arg.ID,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.EvidenceType,
		arg.EvidenceValue,
		arg.StatementChecksum,
		arg.LoreEntryID,
		arg.SuccessorLoreID,
		arg.Status,
		arg.ActorID,
		arg.DecidedAt,
	)
	return err
}

const getLoreReviewDecisionByIdentity = `-- name: GetLoreReviewDecisionByIdentity :one
SELECT
    id, scope_kind, scope_key, evidence_type, evidence_value, statement_checksum,
    lore_entry_id, successor_lore_id, status, actor_id, decided_at
FROM lore_review_decisions
WHERE scope_kind = $1 AND scope_key = $2
  AND evidence_type = $3 AND evidence_value = $4 AND statement_checksum = $5
`

type GetLoreReviewDecisionByIdentityParams struct {
	ScopeKind         string
	ScopeKey          string
	EvidenceType      string
	EvidenceValue     string
	StatementChecksum string
}

func (q *Queries) GetLoreReviewDecisionByIdentity(ctx context.Context, arg GetLoreReviewDecisionByIdentityParams) (LoreReviewDecision, error) {
	row := q.db.QueryRow(ctx, getLoreReviewDecisionByIdentity,
		arg.ScopeKind,
		arg.ScopeKey,
		arg.EvidenceType,
		arg.EvidenceValue,
		arg.StatementChecksum,
	)
	var i LoreReviewDecision
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.EvidenceType,
		&i.EvidenceValue,
		&i.StatementChecksum,
		&i.LoreEntryID,
		&i.SuccessorLoreID,
		&i.Status,
		&i.ActorID,
		&i.DecidedAt,
	)
	return i, err
}

const getLoreReviewDecisionByLoreID = `-- name: GetLoreReviewDecisionByLoreID :one
SELECT
    id, scope_kind, scope_key, evidence_type, evidence_value, statement_checksum,
    lore_entry_id, successor_lore_id, status, actor_id, decided_at
FROM lore_review_decisions
WHERE lore_entry_id = $1
ORDER BY decided_at DESC
LIMIT 1
`

func (q *Queries) GetLoreReviewDecisionByLoreID(ctx context.Context, loreEntryID string) (LoreReviewDecision, error) {
	row := q.db.QueryRow(ctx, getLoreReviewDecisionByLoreID, loreEntryID)
	var i LoreReviewDecision
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeKey,
		&i.EvidenceType,
		&i.EvidenceValue,
		&i.StatementChecksum,
		&i.LoreEntryID,
		&i.SuccessorLoreID,
		&i.Status,
		&i.ActorID,
		&i.DecidedAt,
	)
	return i, err
}

const listLoreReviewDecisionsByScope = `-- name: ListLoreReviewDecisionsByScope :many
SELECT
    id, scope_kind, scope_key, evidence_type, evidence_value, statement_checksum,
    lore_entry_id, successor_lore_id, status, actor_id, decided_at
FROM lore_review_decisions
WHERE scope_kind = $1 AND scope_key = $2
ORDER BY decided_at DESC
`

type ListLoreReviewDecisionsByScopeParams struct {
	ScopeKind string
	ScopeKey  string
}

func (q *Queries) ListLoreReviewDecisionsByScope(ctx context.Context, arg ListLoreReviewDecisionsByScopeParams) ([]LoreReviewDecision, error) {
	rows, err := q.db.Query(ctx, listLoreReviewDecisionsByScope, arg.ScopeKind, arg.ScopeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoreReviewDecision{}
	for rows.Next() {
		var i LoreReviewDecision
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeKey,
			&i.EvidenceType,
			&i.EvidenceValue,
			&i.StatementChecksum,
			&i.LoreEntryID,
			&i.SuccessorLoreID,
			&i.Status,
			&i.ActorID,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
