// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: smoke.sql

package sqlc

import (
	"context"
)

const smoke = `-- name: Smoke :one
SELECT 1::int AS ok
`

func (q *Queries) Smoke(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, smoke)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
